# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('environment', models.SmallIntegerField(choices=[(1, 'Development'), (2, 'Test'), (3, 'Staging'), (4, 'Production')], db_column='environment_id', default=4)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='ResourceProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('value', models.TextField(db_column='value')),
                ('resource', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
            ],
            options={
                'db_table': 'resource_property',
            },
        ),
    ]
