# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('data_type', models.CharField(db_column='data_type', max_length=100)),
            ],
            options={
                'db_table': 'resource_property',
            },
        ),
        migrations.CreateModel(
            name='ResourcePropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(db_column='value')),
                ('resource', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
                ('resource_property', models.ForeignKey(db_column='resource_property_id', on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceProperty')),
            ],
            options={
                'db_table': 'resource_property_value',
            },
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='resource_ptr',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='resource_ptr',
        ),
        migrations.RemoveField(
            model_name='system',
            name='resource_ptr',
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
