# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resourceproperty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='environment',
            field=models.CharField(db_column='environment', max_length=16),
        ),
    ]
